version: '3'
services:
  apis:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - MONGO_HOST=db
      - MONGO_PORT=27017
      - MONGO_DATABASE=admin
      - MONGO_USER=root
      - MONGO_PASSWORD=root
  db:
    image: mongo
    ports:
      - "27017:27017"
    # volumes:
    #   - ${PWD}/mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=admin
  redis:
    image: redis:6.0.2
    ports:
      - "6379:6379"
    # volumes:
    #   - ${PWD}/redis:/data